version: 2.1

executors:
  cypress-executor:
    docker:
      - image: cypress/included:12.10.0  # Use latest Cypress included image
    working_directory: ~/project

jobs:
  install:
    executor: cypress-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  test:
    executor: cypress-executor
    parallelism: 4  # Run tests in 4 parallel containers
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Cypress tests in parallel
          command: |
            npx cypress run --record --key $CYPRESS_RECORD_KEY --parallel --ci-build-id $CIRCLE_WORKFLOW_ID

workflows:
  version: 2
  cypress-tests:
    jobs:
      - install
      - test:
          requires:
            - install
